const API_ROUTES = {
  LOGIN: "/auth/login",
  SIGNUP: "/auth/signup",
  LOGOUT: "/auth/logout",
  ME: "/auth/me",
  FORGOT: "/auth/forgot",
  FORGOT_VERIFY: "/auth/forgot/verify",
  FORGOT_RESET: "/auth/forgot/reset",
  PROFILE: "/users/me",
  PASSWORD: "/users/me/password",
  WORKSPACES: "/workspaces",
  WORKSPACE: (id: string) => `/workspaces/${id}`,
  WORKSPACE_AUDIT: (id: string) => `/workspaces/${id}/audit`,
  WORKSPACE_PROJECTS: (id: string) => `/workspaces/${id}/projects`,
  PROJECT: (id: string) => `/projects/${id}`,
  ENVS: "/envs",
  ENV: (id: string) => `/envs/${id}`,
  PROJECT_ENVS: (id: string) => `/projects/${id}/envs`,
  ENV_VARIABLES: (id: string) => `/envs/${id}/variables`,
  ENV_VARIABLE: (id: string, key: string) => `/envs/${id}/variables/${encodeURIComponent(key)}`,
  ENV_IMPORT: (id: string) => `/envs/${id}/variables/import`,
  USER_ENVS: (id: string) => `/admin/users/${id}/envs`,
  USERS: "/admin/users",
  USER: (id: string) => `/admin/users/${id}`,
  USER_WORKSPACES: (id: string) => `/admin/users/${id}/workspaces`,
  WORKSPACE_INVITES: (id: string) => `/workspaces/${id}/invites`,
  INVITE: (id: string) => `/invites/${id}`,
  INVITE_RESPOND: (id: string) => `/invites/${id}/respond`,
  WORKSPACE_MEMBER: (workspaceId: string, userId: string) => `/workspaces/${workspaceId}/members/${userId}`,
  NOTIFICATIONS: "/notifications",
  NOTIFICATIONS_READ: "/notifications/read",
  DASHBOARD: "/admin/dashboard",
};

export default API_ROUTES;
